### ISSUE TITLE
getting the  apt-key add error can you please help

### ISSUE THREAD

**Issue by mkscala** [torian/ansible-role-filebeat#11]
TASK [filebeat : Elastic APT Key] **********************************************
fatal: [client1]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key add -", "failed": true, "msg": "", "rc": 1, "stderr": "", "stdout": "ERROR: This command can only be used by root.\n", "stdout_lines": ["ERROR: This command can only be used by root."]}

**Comment by torian** [comment]
If you are using the latest release `3.0.2`, this error is due to the fact that I've removed the `become / sudo` options from the tasks that used to have them. Since there's a conflict using `sudo` and `become` altogether, I believe it was better to remove that from the role, and let the user decide what to use.
To overcome this, just use the role with:
```
roles:
  - { role: filebeat, sudo: true }
```
or 
```
roles:
  - { role: filebeat, become: true }
```

Most of the tasks need to be executed by root anyway.
